In [24]:
# UserInput.py
# Given new user input, recommends a new beer
# N is number of reviews
# if N < 10, recommend based on content
# if N >= 10, recommend based on collaborative filtering

In [41]:
import numpy as np
import pandas as pd
import cPickle as pickle

In [42]:
# load matrix here
# with open( , 'rb') as f:
#    user_items = pickle.load(f)

# insert user info here
# new_user = np.repeat(np.nan, user_items.shape[1])
# insert ratings from user input to fill in rated beers

# load beer dictionary here
# with open( , 'rb') as f:
#    beer_names = pickle.load(f)

## Content Based

In [ ]:
# INSERT HERE

 ## CF

In [125]:
# dummy matrix and user input
dummy = np.matrix(np.random.randint(1,6, (15,15)))
homer = np.array([5,np.nan,1,2,3,5,5,5,3,np.nan,1,2,3,5,5])
print dummy, homer

[[5 5 3 1 1 3 4 5 2 2 5 5 5 4 2]
 [2 1 1 1 2 1 5 3 4 3 4 1 4 3 2]
 [1 4 3 1 1 3 4 4 4 2 4 5 5 1 5]
 [3 3 3 4 4 3 5 4 4 4 5 4 5 2 2]
 [3 3 5 5 5 4 5 3 3 3 2 5 3 4 5]
 [2 3 5 2 5 3 4 4 4 2 3 1 2 1 2]
 [1 3 1 3 1 3 5 2 4 3 5 5 1 4 1]
 [1 5 3 2 2 4 2 5 1 3 1 1 2 5 4]
 [5 1 4 2 2 1 4 2 1 3 3 1 3 1 2]
 [1 1 2 1 4 4 5 5 4 5 1 3 2 3 4]
 [4 4 4 2 5 2 4 3 1 4 2 2 3 5 4]
 [4 1 4 4 3 1 2 3 3 3 3 1 5 3 1]
 [1 1 3 3 3 2 1 1 4 5 4 3 4 2 4]
 [1 2 1 5 5 5 4 2 5 3 3 2 4 5 5]
 [2 3 2 2 1 5 2 3 2 1 4 4 3 5 3]] [  5.  nan   1.   2.   3.   5.   5.   5.   3.  nan   1.   2.   3.   5.   5.]


In [147]:
index = np.where(~np.isnan(homer))[0]
missing_index = np.where(np.isnan(homer))[0]
# take items as columns
dummy_red = dummy[:,index]
dummy_miss = dummy[:, missing_index]
homer2 = homer[index]


print index, missing, dummy_red, dummy_miss, homer2

[ 0  2  3  4  5  6  7  8 10 11 12 13 14] [1 9] [[5 3 1 1 3 4 5 2 5 5 5 4 2]
 [2 1 1 2 1 5 3 4 4 1 4 3 2]
 [1 3 1 1 3 4 4 4 4 5 5 1 5]
 [3 3 4 4 3 5 4 4 5 4 5 2 2]
 [3 5 5 5 4 5 3 3 2 5 3 4 5]
 [2 5 2 5 3 4 4 4 3 1 2 1 2]
 [1 1 3 1 3 5 2 4 5 5 1 4 1]
 [1 3 2 2 4 2 5 1 1 1 2 5 4]
 [5 4 2 2 1 4 2 1 3 1 3 1 2]
 [1 2 1 4 4 5 5 4 1 3 2 3 4]
 [4 4 2 5 2 4 3 1 2 2 3 5 4]
 [4 4 4 3 1 2 3 3 3 1 5 3 1]
 [1 3 3 3 2 1 1 4 4 3 4 2 4]
 [1 1 5 5 5 4 2 5 3 2 4 5 5]
 [2 2 2 1 5 2 3 2 4 4 3 5 3]] [[5 2]
 [1 3]
 [4 2]
 [3 4]
 [3 3]
 [3 2]
 [3 3]
 [5 3]
 [1 3]
 [1 5]
 [4 4]
 [1 3]
 [1 5]
 [2 3]
 [3 1]] [ 5.  1.  2.  3.  5.  5.  5.  3.  1.  2.  3.  5.  5.]


In [127]:
# calculate global rating avg mu 
mu = dummy.mean()
print mu

3.02222222222


In [128]:
# normalize via global avg mu
homer3 = (homer2 / (homer2.mean() / mu ))
print homer3
homer3.mean()

[ 4.3654321   0.87308642  1.74617284  2.61925926  4.3654321   4.3654321
  4.3654321   2.61925926  0.87308642  1.74617284  2.61925926  4.3654321
  4.3654321 ]


3.0222222222222217

In [149]:
# compute euclidean distance and cosine similarity
from sklearn.metrics import pairwise as pw
pw_dist = pw.pairwise_distances(dummy_red, homer3)
pw_dist = pw_dist.flatten()
pw_cos = pw.cosine_similarity(dummy_red,homer3).flatten()
print pw_dist, pw_cos

[ 7.06433713  6.46156117  7.79925099  7.52668798  7.08768153  7.40151268
  8.18569483  5.15207448  7.24237666  4.67699068  5.27960622  7.61614075
  8.16736474  6.83351724  5.92172563] [ 0.85485106  0.84126781  0.80108954  0.83822283  0.88343625  0.80228841
  0.75806779  0.90232099  0.79528586  0.92339629  0.90461339  0.78488393
  0.74267958  0.87685966  0.87226095]


/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [130]:
#from sklearn.neighbors import DistanceMetric
#k = DistanceMetric.get_metric('euclidean')
#k.pairwise(dummy_red, homer3)

In [131]:
# smallest distance are nearest neighbors
pw_dist_df =pd.DataFrame([pw_dist]).transpose()
dist_topn = pw_dist_df.nsmallest(5, 0)
dist_topn

0
9   4.676991
7   5.152074
10  5.279606
14  5.921726
1   6.461561

In [132]:
# largest values are most similar users
pw_cos_df = pd.DataFrame([pw_cos]).transpose()
cos_topn = pw_cos_df.nlargest(5,0)
cos_topn

0
9   0.923396
10  0.904613
7   0.902321
4   0.883436
13  0.876860

In [150]:
# turn distance/similarity into weights
# might need to inspect distance again, right now I simply reversed the weights
dist_weights = np.flipud(np.matrix(dist_topn / sum(dist_topn[0])))

cos_weights = np.matrix(cos_topn / sum(cos_topn[0]))
print dist_weights
print cos_weights

[[ 0.23503459]
 [ 0.21539847]
 [ 0.19204184]
 [ 0.18740297]
 [ 0.17012214]]
[[ 0.20562749]
 [ 0.2014448 ]
 [ 0.20093432]
 [ 0.19672895]
 [ 0.19526443]]


In [136]:
dummy_miss

matrix([[5, 2],
        [1, 3],
        [4, 2],
        [3, 4],
        [3, 3],
        [3, 2],
        [3, 3],
        [5, 3],
        [1, 3],
        [1, 5],
        [4, 4],
        [1, 3],
        [1, 5],
        [2, 3],
        [3, 1]])

In [151]:
# get ratings from the top n users for the missing beers
dist_miss_ratings = dummy_miss[dist_topn.index,:] 
cos_miss_ratings = dummy_miss[cos_topn.index,:] 
print dist_miss_ratings
print cos_miss_ratings

[[1 5]
 [5 3]
 [4 4]
 [3 1]
 [1 3]]
[[1 5]
 [4 4]
 [5 3]
 [3 3]
 [2 3]]


In [152]:
# weigh ratings
dist_new_ratings = dist_miss_ratings.transpose() * dist_weights
cos_new_ratings = cos_miss_ratings.transpose() * cos_weights
print dist_new_ratings
print cos_new_ratings

[[ 2.81252531]
 [ 3.28730509]]
[[ 2.99679402]
 [ 3.61269979]]


In [140]:
# find top rating(s)
dist_new_index = np.where(dist_new_ratings == dist_new_ratings.max())[0][0]
cos_new_index = np.where(cos_new_ratings == cos_new_ratings.max())[0][0]
cos_new_index

1

In [148]:

print missing_index[dist_new_index]
print missing_index[cos_new_index]

# match index with beer name

9
9
